// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Entities;

namespace Repositories;

public partial class Shop_WebApiContext : DbContext
{
    public Shop_WebApiContext(DbContextOptions<Shop_WebApiContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.UserFirstName)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("user_first_name");
            entity.Property(e => e.UserLastName)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("user_last_name");
            entity.Property(e => e.UserName)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("user_name");
            entity.Property(e => e.UserPassword)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("user_password");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    internal async Task<User> FindAsync(int id)
    {
        throw new NotImplementedException();
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}